operator -> cortexweave.application.cliAdapter "Runs commands and receives diagnostic/index/search/context output" "CLI"
operator -> agentHarness "Configures or operates the integration"
agentHarness -> cortexweave.application.mcpAdapter "Requests indexed context and records operational state" "MCP / stdio JSON-RPC"
agentHarness -> cortexweave.application.facade "May invoke transport-neutral native Rust API" "Rust API"
operator -> cortexweave "Operates directly through CLI and configuration"
agentHarness -> cortexweave "Uses as a context substrate, not as an agent harness"
cortexweave -> registeredWorkspace "Indexes observed source and documents"
cortexweave -> embeddingService "Generates document and query embeddings"

cortexweave.application.cliAdapter -> cortexweave.application.facade "Invokes application operations after parsing configuration and commands"
cortexweave.application.mcpAdapter -> cortexweave.application.facade "Dispatches validated MCP tool requests"
cortexweave.application.mcpAdapter -> cortexweave.application.workspaceWatcher "Starts and owns watchers only for the MCP process lifetime"

cortexweave.application.facade -> cortexweave.application.workspaceService "Registers, resolves, reports workspace state"
cortexweave.application.facade -> cortexweave.application.indexingService "Requests explicit reindex and file reconciliation"
cortexweave.application.facade -> cortexweave.application.retrievalService "Requests semantic, lexical, or hybrid search"
cortexweave.application.facade -> cortexweave.application.contextService "Requests bounded context or resume packets"
cortexweave.application.facade -> cortexweave.application.structuralService "Requests graph navigation and impact analysis"
cortexweave.application.facade -> cortexweave.application.stateMemoryService "Records and retrieves state, memory, and events"
cortexweave.application.facade -> cortexweave.application.evidenceService "Diagnoses typed evidence"
cortexweave.application.facade -> cortexweave.application.failureNormalizationService "Normalizes decoded failures"
cortexweave.application.facade -> cortexweave.application.episodeService "Starts, mutates, and reads explicit Episodes"
cortexweave.application.facade -> cortexweave.application.consolidationService "Previews and explicitly accepts Experience"
cortexweave.application.facade -> cortexweave.application.experienceSearchService "Searches and explains historical Experience"
cortexweave.application.facade -> cortexweave.application.experienceAssessmentService "Records reviewed assessments and proposes disputes"

cortexweave.application.workspaceService -> cortexweave.database "Persists and resolves workspace identity" "SQL"
cortexweave.application.workspaceScanner -> registeredWorkspace "Reads eligible source files under ignore and pattern rules" "Filesystem"
cortexweave.application.indexingService -> cortexweave.application.workspaceScanner "Scans workspace during explicit reindex"
cortexweave.application.indexingService -> cortexweave.application.analyzerRegistry "Selects analyzer for each relative path"
cortexweave.application.analyzerRegistry -> cortexweave.application.treeSitterAnalyzers "Uses enabled language analyzer for supported paths"
cortexweave.application.analyzerRegistry -> cortexweave.application.genericAnalyzer "Falls back deterministically for other text"
registeredWorkspace -> cortexweave.application.workspaceWatcher "Emits observed filesystem-change notifications while an MCP server owns the watcher" "notify"
cortexweave.application.workspaceWatcher -> cortexweave.application.indexingService "Sends debounced/coalesced changed paths or requests rescan" "Tokio mpsc"
cortexweave.application.indexingService -> cortexweave.application.segmenterBatcher "Segments and batches changed normalized chunks"
cortexweave.application.segmenterBatcher -> cortexweave.application.embeddingAdapter "Generates vectors for changed document segments"
cortexweave.application.embeddingAdapter -> embeddingService "Requests document/query embeddings" "HTTP JSON"
cortexweave.application.indexingService -> cortexweave.database "Atomically persists reconciled documents, chunks, and compatible embeddings" "SQL transaction"
cortexweave.application.indexingService -> cortexweave.application.graphIndexer "Projects normalized analysis after source reconciliation"

cortexweave.application.graphIndexer -> cortexweave.application.symbolRegistry "Reconciles source file and symbol identities"
cortexweave.application.graphIndexer -> cortexweave.application.symbolResolver "Resolves relationship targets deterministically"
cortexweave.application.graphIndexer -> cortexweave.database "Persists graph facts, edges, unresolved uncertainty, revisions, and repair state" "SQL transaction"
cortexweave.application.structuralService -> cortexweave.database "Reads graph projections subject to freshness policy" "SQL"
cortexweave.application.retrievalService -> cortexweave.application.embeddingAdapter "Embeds semantic query"
cortexweave.application.retrievalService -> cortexweave.application.structuralService "Expands structural candidates when intent/configuration permits"
cortexweave.application.retrievalService -> cortexweave.database "Reads compatible vectors, chunk FTS, source metadata, and chunks" "SQL / FTS5"
cortexweave.application.contextService -> cortexweave.application.retrievalService "Acquires code/document candidates"
cortexweave.application.contextService -> cortexweave.application.stateMemoryService "Acquires trusted memory, events, sessions/tasks, checkpoints, working-set, and pins"
cortexweave.application.contextService -> cortexweave.application.structuralService "Acquires bounded structural evidence"
cortexweave.application.contextService -> cortexweave.application.experienceSearchService "Searches eligible historical Experience in a separate budget"
cortexweave.application.contextService -> cortexweave.application.mcpAdapter "Returns bounded ContextPacket and explanation for serialization"
cortexweave.application.mcpAdapter -> agentHarness "Returns MCP tool results and errors"

cortexweave.application.stateMemoryService -> cortexweave.database "Persists memory, state, raw Events, pins, working set, and checkpoints" "SQL transaction"
cortexweave.application.evidenceService -> cortexweave.application.stateMemoryService "Reads append-only raw Events for typed evidence diagnosis"
cortexweave.application.failureNormalizationService -> cortexweave.application.evidenceService "Normalizes only decoded supported evidence"
cortexweave.application.episodeService -> cortexweave.application.stateMemoryService "Associates scoped raw Events to explicit Episodes"
cortexweave.application.episodeService -> cortexweave.database "Persists versioned Episodes, memberships, and request identities" "SQL transaction"
cortexweave.application.consolidationService -> cortexweave.application.evidenceService "Validates typed factual evidence"
cortexweave.application.consolidationService -> cortexweave.application.failureNormalizationService "Builds deterministic failure signatures"
cortexweave.application.consolidationService -> cortexweave.database "Reads terminal Episodes and persists sealed immutable Experience on explicit acceptance" "SQL transaction"
cortexweave.application.experienceSearchService -> cortexweave.database "Reads eligible Experience, FTS, snapshots, lifecycle, and history" "SQL / FTS5"
cortexweave.application.experienceAssessmentService -> cortexweave.application.evidenceService "Validates reviewed-assessment evidence"
cortexweave.application.experienceAssessmentService -> cortexweave.application.failureNormalizationService "Matches deterministic recurring failure signatures"
cortexweave.application.experienceAssessmentService -> cortexweave.application.experienceSearchService "Finds eligible historical records for read-only dispute proposals"
cortexweave.application.experienceAssessmentService -> cortexweave.database "Appends assessments and assessment evidence" "SQL transaction"
